graph TD
    Head[Системные фоновые задачи] --> H
    Head --> N
    Head --> M
    
    H[Каждую минуту] --> H1[Запрос к БД: SELECT * FROM lessons WHERE start_time BETWEEN NOW AND NOW + 31 min AND status = 'scheduled' AND notified = false]
    H1 --> H2{Есть такие занятия?}
        H2 -- Да --> H3[Для каждого: отправить напоминание ученику]
            
        H3[Для каждого: отправить напоминание] --> H4{Успешно отправлено?}
            H4 -- Да --> H5[notified = true]

            H4 -- Нет --> H6_check{Попыток < 3?}
            H6_check -- Да --> H6[increment attempts, notified = false]
            H6_check -- Нет (3 попытки) --> H6_fail[notified = true, status = 'failed_to_notify']
            H6_fail --> H6_fail_alt[Отправить уведомление репетитору: Не удалось уведомить ученика о занятии]
            H6_fail_alt --> H6_log[Записать: уведомление не доставлено ученику]
            
    M[Раз в час] --> M1[Найти все занятия со статусом scheduled]
    M1 --> M2{Для каждого: datetime окончания > now?}
    M2 -- Да --> M3[Проверить: есть ли отметка о проведении?]
    M3 -- Нет отметки --> M4[Обновить статус на missed]
    M3 -- Есть отметка --> M5[Обновить статус на completed]
    M2 -- Нет --> M6[Пропустить занятие]

    N[Раз в день] --> N1[Найти все invite_коды где expires_at < now и is_used = false]
    N1 --> N2[Пометить их как is_used = true]
    N2 --> N3[В лог: ''Очищено X просроченных приглашений'']


