graph TD
    A[Пользователь /start] --> B{Есть ли параметр invite_XXX?}
        B -- Да --> C{Ссылка активна и не истекла?}
            C -- Да, is_used = false и expires_at > now--> D[Найти репетитора по коду]
                D --> E[Создать связь ученик-репетитор]
                E --> E1[Пометить ссылку как is_used = true]
                E1 --> E2[Отправить уведомление репетитору: К вам подключился новый ученик!]
                E2 --> F[Переход в меню ученика]
            C -- Нет, ссылка использована или истекла --> G[Ошибка: ссылка недействительна] 
        B -- Нет --> H{Есть ли user_id в БД?}
            H -- Нет --> I[Запрос роли]
                I --> J[Сохранение роли]
                J --> K{Пользователь репетитор?}
                    K -- Да --> G1[Переход в меню репетитора]
                    K -- Нет --> G2[Переход в меню ученика]
            H -- Да --> K
