graph TD
    A[Пользователь /start] --> B{Есть ли параметр invite_XXX?}
        B -- Да --> C{Ссылка активна и не истекла?}
            C -- Да, is_used = false и expires_at > now--> R[Найти репетитора по коду]
                R --> C_check{ID пользователя == ID репетитора?}
                    C_check -- Да --> G0[Ошибка: нельзя подключиться к самому себе]
                    
                    C_check -- Нет --> C_check1{Существует ли связь ученик-репетитор?}
                        C_check1 -- Да, active --> G1[Ошибка: вы уже подключены к этому репетитору]
                        C_check1 -- Да, inactive --> E0[Восстановить связь: status = 'active']
                        C_check1 -- Нет --> C_check_role
                        C_check_role -- student --> E[Создать связь ученик-репетитор]
                        C_check_role -- tutor --> G2[Ошибка: репетитор не может стать учеником]
                E --> E1[Пометить ссылку как is_used = true]
                E1 --> E2[Отправить уведомление репетитору: К вам подключился новый ученик!]
                E2 --> F[Переход в меню ученика]
            C -- Нет, ссылка использована или истекла --> G3[Ошибка: ссылка недействительна] 
        B -- Нет --> H{Есть ли user_id в БД?}
            H -- Нет --> I[Запрос роли]
                I --> J[Сохранение роли]
                J --> K{Пользователь репетитор?}
                    K -- Да --> Menu_tutor[Переход в меню репетитора]
                    K -- Нет --> Menu_study[Переход в меню ученика]
            H -- Да --> K
