graph TD
    G1[Мои занятия] --> G1a[Показать занятия]
    G1a --> G1a1[Выбрать занятие]
    G1a1 --> G1b[Отменить]
    
    G1b --> G1b_check{Время >= now + 3ч?}
    G1b_check -- Да --> G1b_warning[Предупреждение]
    G1b_warning --> G1b1{Подтверждение?}
    G1b1 -- Да --> G1b2[Списать]
    G1b2 --> G1e[Уведомить репетитора]
    
    G1b_check -- Нет --> G1c{Подтверждение?}
    G1c -- Да --> G1d[status = cancelled]
    G1d --> G1e[Уведомить репетитора]
    
    G1e --> G1f[Сообщение ученику]
    G1f --> G1